version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      # - "./db:/docker-entrypoint-initdb.d"
      - "./db:/var/lib/mysql"
    networks:
      - lamp_docker
  www:
    depends_on:
      - db
    image: pauline/php:mysql # si marche pas bullseye
    volumes:
      - "./:/var/www/html"
    ports:
      - 8081:80
      - 4430:443
    networks:
      - lamp_docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - lamp_docker
    
networks:
  lamp_docker:
    driver: bridge